version: 2
jobs:
  build_5_6:
    docker:
      - image: circleci/php:5.6
    steps:
      - checkout
      - run: find . -type f -name "*.php" -print0 | xargs -L1 -0 php -l
  build_7_0:
    docker:
      - image: circleci/php:7.0
    steps:
      - checkout
      - run: find . -type f -name "*.php" -print0 | xargs -L1 -0 php -l
  build_7_1:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - run: find . -type f -name "*.php" -print0 | xargs -L1 -0 php -l
  build_7_2:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run: find . -type f -name "*.php" -print0 | xargs -L1 -0 php -l
  build_7_3:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - run: find . -type f -name "*.php" -print0 | xargs -L1 -0 php -l
  lint:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - run: git clone -b '2.1.1' https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
      - run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - run: php phpcs.phar -v .
workflows:
  version: 2
  build_and_lint:
    jobs:
      - build_5_6
      - build_7_0
      - build_7_1
      - build_7_2
      - build_7_3
      - lint
